### PR TITLE
Fix for error with BuildCraft 6.3.2

### PR DESCRIPTION
**Pull request by mmelvin0**
I locally applied this to your B7 release (3e1a6e74a1508ba1c0a2955876237e3de06bca57) and it worked well with BuildCraft 6.3.2 + 6.3.1.

I wasn't able to get the current build to work with my current mod pack due to NoClassDefFoundError: org/jruby/embed/jsr223/JRubyEngineFactory, but I assume that is a WIP.

Hope this helps, keep up the great work!

### CODE REVIEW

**Comment by denoflionsx** [comment]
Yeah the Jruby stuff was for another project, but I have superceded that
system with a Groovy based one instead. I will pull this and push out a
release tomorrow.
